/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 17.1 		*/
/*  Created On : 02-дек-2025 15:48:05 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Admin" CASCADE
;

DROP TABLE IF EXISTS "Guide" CASCADE
;

DROP TABLE IF EXISTS "Payment" CASCADE
;

DROP TABLE IF EXISTS "Record" CASCADE
;

DROP TABLE IF EXISTS "Tour" CASCADE
;

DROP TABLE IF EXISTS "Tourist" CASCADE
;

DROP TABLE IF EXISTS "User" CASCADE
;

/* Create Tables */

CREATE TABLE "Admin"
(
	"AdminID" int NOT NULL,
	"Name" varchar NULL
)
;

CREATE TABLE "Guide"
(
	"GuideID" int NOT NULL,
	"Name" varchar NULL
)
;

CREATE TABLE "Payment"
(
	"PaymentID" int NOT NULL,
	"PaymentDate" date NULL,
	"Status" varchar NULL,
	"Amount" float NULL,
	"RecordID" int NULL
)
;

CREATE TABLE "Record"
(
	"RecordID" int NOT NULL,
	"RecordDate" date NULL,
	"Status" varchar NULL,
	"PaymentID" int NULL,
	"TourID" int NULL
)
;

CREATE TABLE "Tour"
(
	"TourID" int NOT NULL,
	"Date" date NULL,
	"Location" varchar NULL,
	"Title" varchar NULL,
	"Description" char NULL,
	"AdminID" int NULL,
	"GuideID" int NULL
)
;

CREATE TABLE "Tourist"
(
	name char NULL
)
;

CREATE TABLE "User"
(
	"UserID" int NOT NULL,
	"Name" varchar NULL,
	"Email" varchar NULL,
	"Role" varchar NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Admin" ADD CONSTRAINT "PK_Admin"
	PRIMARY KEY ("AdminID")
;

ALTER TABLE "Guide" ADD CONSTRAINT "PK_Guide"
	PRIMARY KEY ("GuideID")
;

ALTER TABLE "Payment" ADD CONSTRAINT "PK_Payment"
	PRIMARY KEY ("PaymentID")
;

ALTER TABLE "Record" ADD CONSTRAINT "PK_Record"
	PRIMARY KEY ("RecordID")
;

ALTER TABLE "Tour" ADD CONSTRAINT "PK_Tour"
	PRIMARY KEY ("TourID")
;

ALTER TABLE "User" ADD CONSTRAINT "PK_User"
	PRIMARY KEY ("UserID")
;

/* Create Foreign Key Constraints */

ALTER TABLE "Payment" ADD CONSTRAINT "FK_Record_Payment"
	FOREIGN KEY ("RecordID") REFERENCES "Record" ("RecordID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Record" ADD CONSTRAINT "FK_Tour_Record"
	FOREIGN KEY ("TourID") REFERENCES "Tour" ("TourID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Tour" ADD CONSTRAINT "FK_Admin_Tour"
	FOREIGN KEY ("AdminID") REFERENCES "Admin" ("AdminID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Tour" ADD CONSTRAINT "FK_Guide_Tour"
	FOREIGN KEY ("GuideID") REFERENCES "Guide" ("GuideID") ON DELETE No Action ON UPDATE No Action
;
