/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 17.1 		*/
/*  Created On : 02-дек-2025 16:15:04 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Views */

DROP VIEW IF EXISTS "VIEW_A" CASCADE
;

/* Drop Tables */

DROP TABLE IF EXISTS "TABLE_A" CASCADE
;

DROP TABLE IF EXISTS "TABLE_B" CASCADE
;

DROP TABLE IF EXISTS "TABLE_C" CASCADE
;

/* Create Tables */

CREATE TABLE "TABLE_A"
(
	"ID" integer NOT NULL,
	"COLUMN_A" integer NULL,
	"COLUMN B" integer NULL
)
;

CREATE TABLE "TABLE_B"
(
	"COLUMN_A" integer NULL,
	"COLUMN B" integer NULL
)
;

CREATE TABLE "TABLE_C"
(
	"COLUMN_A" integer NULL,
	"COLUMN B" integer NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "TABLE_A" ADD CONSTRAINT "PK_Table A"
	PRIMARY KEY ("ID")
;

/* Create Foreign Key Constraints */

ALTER TABLE "TABLE_B" ADD CONSTRAINT "FK_TABLE_B_TABLE_A"
	FOREIGN KEY ("COLUMN_A") REFERENCES "TABLE_A" ("ID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "TABLE_C" ADD CONSTRAINT "FK_TABLE_C_TABLE_A"
	FOREIGN KEY ("COLUMN_A") REFERENCES "TABLE_A" ("ID") ON DELETE No Action ON UPDATE No Action
;

/* Create Views */

CREATE VIEW "VIEW_A" AS 
/* SQL statements defining VIEW_A */
;

COMMENT ON VIEW "VIEW_A"
	IS '[Business description of the purpose of the view.]'
;
