///////////////////////////////////////////////////////////
//  Payment.cs
//  Implementation of the Class Payment
//  Generated by Enterprise Architect
//  Created on:      02-дек-2025 14:44:30
//  Original author: CZA097
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Payment {

	private float amount;
	private int id;

	public Payment(){

	}

	~Payment(){

	}

	/// 
	/// <param name="value"></param>
	public boolean process(float value){

		return null;
	}

}//end Payment