///////////////////////////////////////////////////////////
//  Tour.cs
//  Implementation of the Class Tour
//  Generated by Enterprise Architect
//  Created on:      02-дек-2025 14:44:34
//  Original author: CZA097
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Tour : Payment {

	private date date;
	private int id;
	private string title;

	public Tour(){

	}

	~Tour(){

	}

	public String getTitle(){

		return "";
	}

	/// 
	/// <param name="t"></param>
	public void setTitle(string t){

	}

}//end Tour